name: Build Android Natives

on:
  workflow_dispatch:

jobs:
  natives-android:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r28c

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android natives
        run: ./gradlew clean jniGen jnigenBuildAndroid

      - name: Pack artifacts
        run: |
          find . -name "*.a" -o -name "*.dll" -o -name "*.dylib" -o -name "*.so" | grep "libs" > native-files-list
          zip natives-android.zip -@ < native-files-list

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: natives-android.zip
          path: natives-android.zip
