name: Build LibGDX Native Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: Set up JDK 17  
        uses: actions/setup-java@v3  
        with:  
          java-version: '17'  
          distribution: 'temurin'  
          cache: gradle  

      - name: Setup Android NDK  
        uses: nttld/setup-ndk@v1.5.0  
        with:  
          ndk-version: r28c  

      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew  

      - name: Build gdx-box2d  
        run: |  
          cd extensions/gdx-box2d/gdx-box2d/jni/Box2D  
          mkdir -p build && cd build  
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \  
                   -DANDROID_ABI=arm64-v8a \  
                   -DANDROID_PLATFORM=android-21  
          cmake --build .  
          mkdir -p $GITHUB_WORKSPACE/artifacts/arm64-v8a  
          cp libgdx-box2d.so $GITHUB_WORKSPACE/artifacts/arm64-v8a/  

      - name: Build libgdx  
        run: |  
          cd backends/gdx-backend-android/jni  
          mkdir -p build && cd build  
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \  
                   -DANDROID_ABI=arm64-v8a \  
                   -DANDROID_PLATFORM=android-21  
          cmake --build .  
          mkdir -p $GITHUB_WORKSPACE/artifacts/arm64-v8a  
          cp libgdx.so $GITHUB_WORKSPACE/artifacts/arm64-v8a/  

      - name: Upload artifacts  
        uses: actions/upload-artifact@v3  
        with:  
          name: gdx-libs  
          path: artifacts/
